// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono, VT323 } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vt323 = VT323({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-vt323',
});

export const metadata: Metadata = {
  title: "Alex's Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const nostalgiaCookie = cookieStore.get('nostalgia');
  const isNostalgia = nostalgiaCookie?.value === 'true';
  const bodyClassName = `${geistSans.variable} ${geistMono.variable} antialiased ${isNostalgia ? vt323.className : ''}`;

  return (
    <html lang="en">
      <body className={bodyClassName}>
        {children}
      </body>
    </html>
  );
}